### ISSUE TITLE
Too wide for old iphone screens.

### ISSUE THREAD

**Issue by Anonymoosed** [bleistivt/minusbaseline#1]
Too wide for old iphone screens, with needless horizontal scrolling.

**Comment by bleistivt** [comment]
What iphone generation are you using and do you know the screen resolution by any chance?

**Comment by Anonymoosed** [comment]
iPhone 4 and 4s has 960-by-640 resolution. Thanks.

**Comment by bleistivt** [comment]
773dd4fd98edb4af0ea61f2124614c6394b6a5f6 should fix it

**Comment by Anonymoosed** [comment]
Thank you!.
